---
pages:
- _index.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- type: text
  name: subtitle
  label: Subtitle
  default: ''
- name: image
  label: Image
  type: file
  hidden: false
  default: ''
- type: number
  name: imageTint
  label: Image Tint
  config:
    min: '0'
    max: '100'
- type: text
  name: imageTintGradient
  label: Image Tint Gradient
- name: type
  label: Type
  type: text
  hidden: true
  default: page